# Generated by Django 4.1.2 on 2022-10-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discription', models.TextField()),
            ],
        ),
    ]
